# Publicly credit Sauce Labs because they generously support open source
# projects.
name: Frontend Tests

on:
  workflow_call:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Setup etherpad
        uses: ./.github/workflows/setup-etherpad-with-plugins.yml
      # Etherpad core dependencies must be installed after installing the
      # plugin's dependencies, otherwise npm will try to hoist common
      # dependencies by removing them from src/node_modules and installing them
      # in the top-level node_modules. As of v6.14.10, npm's hoist logic appears
      # to be buggy, because it sometimes removes dependencies from
      # src/node_modules but fails to add them to the top-level node_modules.
      # Even if npm correctly hoists the dependencies, the hoisting seems to
      # confuse tools such as `npm outdated`, `npm update`, and some ESLint
      # rules.
      - name: Create settings.json
        run: cp ./src/tests/settings.json settings.json
      - name: Run the frontend tests
        shell: bash
        run: |
          pnpm run dev &
          connected=false
          can_connect() {
          curl -sSfo /dev/null http://localhost:9001/ || return 1
          connected=true
          }
          now() { date +%s; }
          start=$(now)
          while [ $(($(now) - $start)) -le 15 ] && ! can_connect; do
          sleep 1
          done
          cd src
          pnpm exec playwright install chromium  --with-deps
          pnpm run test-ui --project=chromium
