on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true


jobs:
  backend:
    uses: ./.github/workflows/backend-tests-plugins.yml
    secrets: inherit
  frontend:
    uses: ./.github/workflows/frontend-tests-plugins.yml
    secrets: inherit
  release:
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    needs:
      - backend
      - frontend
    uses: ./.github/workflows/npmpublish-plugins.yml
    secrets: inherit
